<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrived.proto

namespace GPBMetadata;

class Contrived
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3010a0f636f6e7472697665642e70726f746f12077365727669636522" .
            "270a17436f6e7472697665644d65737361676552657175657374120c0a04" .
            "626f647918012001280922280a18436f6e7472697665644d657373616765" .
            "526573706f6e7365120c0a04626f6479180120012809326c0a10436f6e74" .
            "72697665645365727669636512580a0f436f6e7472697665644d6574686f" .
            "6412202e736572766963652e436f6e7472697665644d6573736167655265" .
            "71756573741a212e736572766963652e436f6e7472697665644d65737361" .
            "6765526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

