<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contrived.proto

namespace Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>service.ContrivedMessageRequest</code>
 */
class ContrivedMessageRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string body = 1;</code>
     */
    private $body = '';

    public function __construct() {
        \GPBMetadata\Contrived::initOnce();
        parent::__construct();
    }

    /**
     * <code>string body = 1;</code>
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * <code>string body = 1;</code>
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;
    }

}

